{
  "NServiceBus.MessageId": "50f51d70-aeec-44db-b7dd-aac1010565f8",
  "NServiceBus.MessageIntent": "Publish",
  "NServiceBus.RelatedTo": "8e4c49ea-ac36-47e0-9739-aac1010565e0",
  "NServiceBus.ConversationId": "3d3cb4bd-d808-4890-b247-aac1010565e0",
  "NServiceBus.CorrelationId": "8e4c49ea-ac36-47e0-9739-aac1010565e0",
  "NServiceBus.OriginatingMachine": "2H81TQ2",
  "NServiceBus.OriginatingEndpoint": "PublisherOne",
  "$.diagnostics.originating.hostid": "2edd0c1bcb4f40655b9d87b131c44c4e",
  "NServiceBus.ReplyToAddress": "PublisherOne",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "MessageBusFun.Core.PublisherRegistered, MessageBusFun.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.Version": "7.1.10",
  "NServiceBus.TimeSent": "2019-09-07 15:51:43:379031 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.NullReferenceException",
  "NServiceBus.Retries.Timestamp": "2019-09-07 15:52:20:176225 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "Object reference not set to an instance of an object.",
  "NServiceBus.ExceptionInfo.Source": "ConsoleApp1",
  "NServiceBus.ExceptionInfo.StackTrace": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Channel.PublisherRegisteredHandler.Handle(PublisherRegistered message, IMessageHandlerContext context) in C:\\Users\\Chetana.Prabhu\\Desktop\\BEAZLEYGroup\\MessageBusFun\\MessageBusFun\\ConsoleApp1\\PublisherRegisteredHandler.cs:line 20\r\n   at lambda_method(Closure , Object , Object , IMessageHandlerContext )\r\n   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext) in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\Incoming\\MessageHandler.cs:line 43\r\n   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context) in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\Incoming\\InvokeHandlerTerminator.cs:line 16\r\n   at (Closure`2 , IInvokeHandlerContext )\r\n   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\Incoming\\LoadHandlersConnector.cs:line 48\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\Incoming\\DeserializeLogicalMessagesConnector.cs:line 33\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Performance\\Statistics\\ProcessingStatisticsBehavior.cs:line 25\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\Incoming\\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 37\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Pipeline\\MainPipelineExecutor.cs:line 34\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext() in C:\\BuildAgent\\work\\ed946b9f0e4aae01\\src\\NServiceBus.Core\\Transports\\Learning\\LearningTransportMessagePump.cs:line 279",
  "NServiceBus.TimeOfFailure": "2019-09-07 15:52:52:608499 Z",
  "NServiceBus.FailedQ": "Consumer",
  "NServiceBus.ProcessingMachine": "2H81TQ2",
  "NServiceBus.ProcessingEndpoint": "Consumer",
  "$.diagnostics.hostid": "e2122cc92ee3498e0a3e8da6efa9cb3f",
  "$.diagnostics.hostdisplayname": "2H81TQ2"
}